In [4]:
import numpy as np
import pandas as pd
import re
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.naive_bayes import MultinomialNB
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
df=pd.read_csv("fake_and_real_news.csv")
df.head()


Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [6]:
df.shape

(9900, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9900 entries, 0 to 9899
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Text    9900 non-null   object
 1   label   9900 non-null   object
dtypes: object(2)
memory usage: 154.8+ KB


In [8]:
len(df['Text'])

9900

In [9]:
ps=PorterStemmer()

In [ ]:
##Text preprocessing
corpus=[]
for i in range(len(df['Text'])):
  news=re.sub('[^a-zA-Z]',' ',df['Text'][i])
  news=news.lower()
  news=news.split()
  news=[ps.stem(word) for word in news if word not in set(stopwords.words('english'))]
  news=' '.join(news)
  corpus.append(news)


In [ ]:
type(corpus)

list

In [ ]:
##create a bag of words
df['label'].value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['label']=le.fit_transform(df['label'])

In [ ]:
df

Text  label
0      Top Trump Surrogate BRUTALLY Stabs Him In The...      0
1     U.S. conservative leader optimistic of common ...      1
2     Trump proposes U.S. tax overhaul, stirs concer...      1
3      Court Forces Ohio To Allow Millions Of Illega...      0
4     Democrats say Trump agrees to work on immigrat...      1
...                                                 ...    ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...      0
9896  Trump consults Republican senators on Fed chie...      1
9897  Trump lawyers say judge lacks jurisdiction for...      1
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...      0
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...      0

[9900 rows x 2 columns]

In [ ]:
df['label'].isnull().sum()

np.int64(0)

In [ ]:
y=df['label']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2,random_state=0)

In [ ]:
len(X_train)

7920

In [ ]:
len(X_test)

1980

In [ ]:
len(y_train)

7920

In [ ]:
len(y_test)

1980

In [ ]:
###Text->vectors
vectorizer=TfidfVectorizer()
X_train=vectorizer.fit_transform(X_train).toarray()
X_test=vectorizer.transform(X_test).toarray()

In [ ]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
vectorizer.vocabulary_

{'trump': 32045,
 'say': 27404,
 'travel': 31887,
 'ban': 2171,
 'larger': 17353,
 'tougher': 31740,
 'specif': 29310,
 'washington': 34169,
 'reuter': 26208,
 'presid': 24370,
 'donald': 8237,
 'friday': 11115,
 'push': 24823,
 'back': 2028,
 'effort': 8968,
 'rein': 25858,
 'administr': 326,
 'peopl': 23332,
 'enter': 9393,
 'unit': 32911,
 'state': 29641,
 'six': 28651,
 'muslim': 20734,
 'major': 18686,
 'countri': 6350,
 'also': 886,
 'limit': 17929,
 'refuge': 25790,
 'controversi': 6133,
 'even': 9727,
 'wider': 34592,
 'far': 10125,
 'stupidli': 30069,
 'would': 34945,
 'polit': 23986,
 'correct': 6252,
 'said': 27136,
 'twitter': 32328,
 'post': 24139,
 'come': 5788,
 'ahead': 536,
 'key': 16534,
 'suprem': 30290,
 'court': 6363,
 'hear': 13167,
 'next': 21299,
 'month': 20324,
 'constitution': 6073,
 'execut': 9834,
 'order': 22418,
 'watch': 34187,
 'wwii': 35071,
 'vet': 33630,
 'shame': 28119,
 'hell': 13274,
 'insult': 14851,
 'pow': 24202,
 'militari': 19887,
 'john': 15

In [ ]:
fake_news_detection=MultinomialNB()
fake_news_detection.fit(X_train,y_train)

MultinomialNB()

In [ ]:
y_pred=fake_news_detection.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
accuracy_score=accuracy_score(y_test,y_pred)
confusion_matrix=confusion_matrix(y_test,y_pred)
classification_report=classification_report(y_test,y_pred)

In [ ]:
print("Accuracy Score: ",accuracy_score)
print("Confusion Matrix: ",confusion_matrix)
print("Classification Report: ",classification_report)

Accuracy Score:  0.9515151515151515
Confusion Matrix:  [[949  68]
 [ 28 935]]
Classification Report:                precision    recall  f1-score   support

           0       0.97      0.93      0.95      1017
           1       0.93      0.97      0.95       963

    accuracy                           0.95      1980
   macro avg       0.95      0.95      0.95      1980
weighted avg       0.95      0.95      0.95      1980



In [ ]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred_logic=logistic.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred_logic)

# Generate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred_logic)

# Generate classification report
classification_rep = classification_report(y_test, y_pred_logic)

# Print the results
print("Logistic Regression Accuracy Score:", accuracy)
print("Logistic Regression Confusion Matrix:\n", confusion_mat)
print("Logistic Regression Classification Report:\n", classification_rep)

Logistic Regression Accuracy Score: 0.9878787878787879
Logistic Regression Confusion Matrix:
 [[997  20]
 [  4 959]]
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99      1017
           1       0.98      1.00      0.99       963

    accuracy                           0.99      1980
   macro avg       0.99      0.99      0.99      1980
weighted avg       0.99      0.99      0.99      1980



In [ ]:
import pickle

# Save the vectorizer
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

# Save Naive Bayes classifier
with open('nb_model.pkl', 'wb') as f:
    pickle.dump(fake_news_detection, f)

# Save Logistic Regression classifier
with open('logistic_model.pkl', 'wb') as f:
    pickle.dump(logistic, f)

In [ ]:
import pickle

# Load the vectorizer
with open('tfidf_vectorizer.pkl', 'rb') as f:
    vectorizer = pickle.load(f)

# Load the Naive Bayes model
with open('nb_model.pkl', 'rb') as f:
    fake_news_detection = pickle.load(f)

# Alternatively, load the Logistic Regression model
with open('logistic_model.pkl', 'rb') as f:
    logistic = pickle.load(f)

In [ ]:
# Example new news article
new_news = "Breaking news: The government has announced new policies today."

# Preprocess the new news similar to training
import re
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

ps = PorterStemmer()

# Clean and preprocess
news = re.sub('[^a-zA-Z]', ' ', new_news)
news = news.lower()
news = news.split()
news = [ps.stem(word) for word in news if word not in set(stopwords.words('english'))]
processed_news = ' '.join(news)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# Transform using the same vectorizer
vectorized_news = vectorizer.transform([processed_news]).toarray()

# Predict with Naive Bayes
nb_prediction = fake_news_detection.predict(vectorized_news)

# Or predict with Logistic Regression
logistic_prediction = logistic.predict(vectorized_news)

# Output
if nb_prediction[0] == 0:
    print("Naive Bayes Prediction: Fake News")
else:
    print("Naive Bayes Prediction: Real News")

if logistic_prediction[0] == 0:
    print("Logistic Regression Prediction: Fake News")
else:
    print("Logistic Regression Prediction: Real News")

Naive Bayes Prediction: Real News
Logistic Regression Prediction: Real News
